# Site settings
title: netbuk.blog
email: christian@netbuk.de
description: kleiner privater technik-blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://netbuk.github.io" # the base hostname & protocol for your site
twitter_username: der__k
github_username:  netbuk

# Build settings
markdown: kramdown
